// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://wayyxxqydxpfxbmvzbly.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6IndheXl4eHF5ZHhwZnhibXZ6Ymx5Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3MzUwMjM4MzcsImV4cCI6MjA1MDU5OTgzN30.GD7YwPus21VKaux_7oT_Vo7g7c4FZHw23rggj5ckZyE";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);